@extends('layouts.app')
@section('content')
<section id="terms-of-service" class="py-10">
  <div class="container mx-auto flex flex-col gap-4">
    <h1 class="text-center font-bold text-5xl">Privacy Policy</h1>
    <p class="italic mb-5">Last updated: December 8, 2023 </p>
    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Website and tells You about Your privacy rights and how the law protects You. </p>
    <p>We use Your Personal data to provide and improve the Website. By using the Website, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
    <h1 class="text-center font-bold text-xl uppercase mt-10">INTERPRETATION AND DEFINITIONS </h1>
    <div>
      <h3 class="font-bold text-xl mt-5">Interpretation</h3>
      <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>
      <h3 class="font-bold text-xl mt-5">Definitions</h3>
      <p class="italic">For the purposes of this Privacy Policy:</p>
      <p class="mt-3"><span class="font-semibold">“Account”</span> means a unique account created for You to access our Service or parts of our Service.</p>
      <p class="mt-3"><span class="font-semibold">“Affiliate”</span> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
      <p class="mt-3"><span class="font-semibold">“Company”</span> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Lurtsema Communications, 201 Barrow Street, Suite 103, Anchorage, AK 99501.</p>
      <p class="mt-3"><span class="font-semibold">“Cookies”</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
      <p class="mt-3"><span class="font-semibold">“Country” </span> refers to: Alaska, United States</p>
      <p class="mt-3"><span class="font-semibold">“Device” </span> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</p>
      <p class="mt-3"><span class="font-semibold">“Personal Data” </span> is any information that relates to an identified or identifiable individual.</p>
      <p class="mt-3"><span class="font-semibold">“Usage Data” </span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
      <p class="mt-3"><span class="font-semibold">“Website” </span> refers to Lurtsema Communications Website, accessible from <a class="underline" href="{{ url('/') }}">{{ url('/') }}</a> </p>
      <p class="mt-3"><span class="font-semibold">“Opt-in box” </span> refers to a confirmation checkbox where the company provides users with the option to choose whether they wish to receive text messages related to the Contact form. </p>
      <p class="mt-3"><span class="font-semibold">“Third Party” </span> refers to any entity or individual that is not directly associated with the Company. This includes external organizations, companies, individuals, or any other parties that are not part of our business or service operations. </p>
      <p class="mt-3"><span class="font-semibold">“You” </span> mean the individual accessing or using the Service, the company, or other legal entity on behalf of which such individual is accessing or using the Website, as applicable. </p>
    </div>
    <h1 class="text-center font-bold text-xl uppercase mt-10">COLLECTING AND USING YOUR PERSONAL DATA TYPES OF DATA COLLECTED <h1>
    <div>
      <h3 class="font-bold text-xl mt-5">Personal Data</h3>
      <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: </p>
      <ul class="list-disc list-outside px-5">
        <li class="">Email address</li>
        <li class="">First name and last name</li>
        <li class="">Phone number</li>
        <li class="">Address, State, Province, ZIP/Postal code, City</li>
      </ul>
      <h3 class="font-bold text-xl mt-10">Usage Data</h3>
      <p>Usage Data is collected automatically when using the Website.  Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. </p>
      <p class="mt-5">When You access the Website by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.  </p>
      <p class="mt-5">We may also collect information that Your browser sends whenever You visit our Website or when You access the Website by or through a mobile device  </p>
      <h3 class="font-bold text-xl mt-10">Web Beacons</h3>
      <p>Certain sections of our Website and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).  </p>
    </div>
    <h1 class="text-center font-bold text-xl uppercase mt-10">COOKIES POLICY / NOTICE ACCEPTANCE COOKIES  <h1>
    <div>
      <h3 class="font-bold text-xl mt-5 underline">TRACKING TECHNOLOGIES AND COOKIES</h3>
      <p>We use Cookies and similar tracking technologies to track the activity on Our Website and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Website. The technologies We use may include:</p>
      <ul class="list-disc list-outside px-5 mt-5">
        <li><span class="font-semibold">Cookies or Browser Cookies.</span>A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Website. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies. </li>
      </ul>
      <p class="mt-5">Cookies can be <span class="font-semibold">“Persistent”</span> or <span class="font-semibold">“Session” Cookies</span>. Persistent <span class="font-semibold">Cookies</span> remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.   </p>
      <p class="mt-5 font-semibold">We use both Session and Persistent Cookies for the purposes set out below:</p>
      <ul class="list-disc list-outside px-5 my-5">
        <li>
          <span class="font-semibold">Necessary / Essential Cookies</span> <br>
          Type: <span class="font-semibold">Session Cookies </span><br>
          Administered by: Us
        </li>
      </ul>
      <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and  We only use these Cookies to provide You with those services  </p>
      <p class="mt-5">Type: <span class="font-semibold">Persistent Cookies</span></p>
      <p>Administered by: Us</p>
      <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website. </p>
      <ul class="list-disc list-outside px-5 my-5">
        <li>
          <span class="font-semibold">Functionality Cookies</span> <br>
          Type: <span class="font-semibold">Persistent Cookies </span><br>
          Administered by: Us<br>
          Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.        </li>
      </ul>
    </div>
    <div>
      <h3 class="font-bold text-xl mt-10 underline">USE OF YOUR PERSONAL DATA  </h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul class="list-disc list-outside px-5">
        <li>To <span class="font-semibold">provide and maintain our Website</span>, including to monitor the usage of our Website.</li>
        <li>To <span class="font-semibold">manage Your Account:</span> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Website that are available to You as a registered user.</li>
        <li>For the <span class="font-semibold">performance of a contract: </span>the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Website. </li>
        <li>To <span class="font-semibold">contact You:</span>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation. </li>
        <li>To <span class="font-semibold"> provide You with news, special offers and general information about other goods, services and events which we offer </span>that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
        <li>To <span class="font-semibold">manage Your requests: </span>To attend and manage Your requests to Us. </li>
        <li>For <span class="font-semibold">business transfers: </span>We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred with Your consent.</li>
      </ul>
      <p class="mt-5">This information cannot be used for any 3rd party purposes. We also refrain from sharing or transferring your personal information with any external parties. We may share Your personal information in the following situations:</p>
      <ul class="list-disc list-outside px-5">
        <li>Opt-in data will not be shared with any 3rd party except for with vendors, consultants, and other service providers who need access to carry out work on your behalf.</li>
        <li>With Service <span class="font-semibold">Providers:</span> We may share Your personal information with Service Providers who work on our behalf to monitor and analyze the use of our Website, to contact You  </li>
        <li><span class="font-semibold">With Affiliates:</span> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, essential venture partners, consultants, and other service providers who require Your Consent to facilitate work on our behalf. </li>
        <li>With<span class="font-semibold">Your consent:</span> We may disclose Your personal information for any other purpose with Your consent. </li>
      </ul>
    </div>
    <div>
      <h3 class="font-bold text-xl mt-10">Retention of Your Personal Data</h3>
      <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws and any third-party), resolve disputes, and enforce our legal agreements and policies.</p>
      <p class="mt-5">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.  </p>
    </div>
    <div>
      <h3 class="font-bold text-xl mt-10">Transfer of Your Personal Data  </h3>
      <p>Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
      <p class="mt-5">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
      The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to any third party organization or a country unless there are adequate controls in place including the security of Your data and other personal information.   </p>
    </div>
    <div>
      <h3 class="font-bold text-xl mt-10">Delete Your Personal Data </h3>
      <p>You have the right to delete or request that We assist in deleting the Personal Data We have collected about You. Our Website may give You the ability to delete certain information about You from within the Service. You may update, amend, or delete Your information at any time by signing in to Your Account if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us. Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.  

      </p>
      <p class="mt-5">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.  

        The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to any third party organization or a country unless there are adequate controls in place including the security of Your data and other personal information.   </p>
    </div>
    <div>
      <h3 class="font-bold text-xl mt-10 underline">DISCLOSURE OF YOUR PERSONAL DATA </h3>
      <h3 class="font-bold text-xl mt-5">Business Transactions</h3>
      <p class="">If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy. </p>
      <h3 class="font-bold text-xl mt-5">Law enforcement</h3>
      <p class="">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).  </p>
      <h3 class="font-bold text-xl mt-5">Other legal requirements</h3>
      <p class="">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: </p>
      <ul class="list-disc ml-5">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public </li>
        <li>Protect against legal liability  </li>
      </ul>
      <h3 class="font-bold text-xl mt-5">Security of Your Personal Data </h3>
      <p class="">Ensuring the Security of Your Personal Data is Our Top Priority. Our website features a comprehensive Privacy Policy that explicitly affirms our commitment to safeguarding your information. This policy explicitly states that opt-in data will never be disclosed to any third party, except for essential vendors, consultants, and other service providers who need access on your behalf. Rest assured that this information will not be utilized for any other purposes. If you find any missing components or have any questions, kindly contact Lurtsema Communications for assistance.</p>
    </div>
    <div>
      <h3 class="font-bold text-xl mt-10 underline">CHILDREN’S PRIVACY </h3>
      <p>Our Website does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.  </p>
      <p class="mt-5">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information.  </p>
    </div>
    <div>
      <h3 class="font-bold text-xl mt-10 underline">LINKS TO OTHER WEBSITES  </h3>
      <p>Our Website may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third-party’s site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.  </p>
    </div>
    <div>
      <h3 class="font-bold text-xl mt-10 underline">CHANGES TO THIS PRIVACY POLICY    </h3>
      <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.   </p>
      <p class="mt-5">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy.  </p>
      <p class="mt-5">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.  </p>
    </div>
  </div>
</section>
@endsection
@section('scripts')
@endsection